### ISSUE TITLE
Using touchpad gestures breaks the desktop

### ISSUE THREAD

**Issue by Jeffser** [material-shell/material-shell#969]
When I use any touchpad gestures the gnome default action is performed

We could make custom gestures if it's possible

**To Reproduce**
- Occurs on:
  - [x] X.Org
  - [x] Wayland
- GNOME Shell version: 44.0
- Distro: Fedora Workstation 38

**Comment by iberianpig** [comment]
> https://gist.github.com/iberianpig/6e7049a02489950f570b4a27cff8df5e

Following scripts change the finger count of gestures.

```sh
function gnome-wayland-change-finger-count() {
  local finger_count=$1
  case "${finger_count}" in
    3|4|5)
      echo "changing finger count to ${finger_count}"

      # check if the file we want to customize is in the gresource list
      if gresource list /usr/lib/gnome-shell/libgnome-shell.so | grep -q 'swipetracker.js'; then
        # create a folder to hold your custom overlays
        mkdir -p ~/.gnome-shell-custom-overlays/ui

        # extract the file we want to customize
        gresource extract /usr/lib/gnome-shell/libgnome-shell.so /org/gnome/shell/ui/swipetracker.js > ~/.gnome-shell-custom-overlays/ui/swipetracker.js

        # change the gesture_finger_count value
        sed -i "s:const gesture_finger_count = [[:digit:]];:const gesture_finger_count = ${finger_count};:" ~/.gnome-shell-custom-overlays/ui/swipetracker.js

        # set the g_resource_overlays environment variable in ~/.config/environment.d/gnome-shell-overlay.conf
        mkdir -p ~/.config/environment.d
        echo 'g_resource_overlays="/org/gnome/shell/ui/swipetracker.js=$home/.gnome-shell-custom-overlays/ui/swipetracker.js"' > ~/.config/environment.d/gnome-shell-overlay.conf
      else 
        echo "swipetracker.js not found in libgnome-shell.so" > /tmp/swipetracker.log
      fi
      ;;
    *)
      echo "usage: $0 [3|4|5]"
  esac
}
```


And customize touchpad gestures with Fusuma and plugins

- https://github.com/iberianpig/fusuma
- https://github.com/iberianpig/fusuma-plugin-keypress
- https://github.com/iberianpig/fusuma-plugin-sendkey


```yaml
plugin:
  inputs:
    libinput_command_input:
      show-keycodes: true

swipe:
  4:
    up:
      sendkey: 'LEFTMETA+S'
      keypress:
        LEFTSHIFT:
          sendkey: "LEFTMETA+DOWN"
          clearmodifiers: true
        LEFTMETA:
          sendkey: "LEFTMETA+LEFTSHIFT+DOWN"
          clearmodifiers: true
    down:
      sendkey: 'LEFTMETA+W'
      keypress:
        LEFTSHIFT:
          sendkey: "LEFTMETA+UP"
          clearmodifiers: true
        LEFTMETA:
          sendkey: "LEFTMETA+LEFTSHIFT+UP"
          clearmodifiers: true
    left:
      sendkey: "LEFTMETA+D"
      keypress:
        LEFTSHIFT:
          sendkey: "LEFTMETA+RIGHT"
          clearmodifiers: true
    right:
      sendkey: "LEFTMETA+A"
      keypress:
        LEFTSHIFT:
          sendkey: "LEFTMETA+LEFT"
          clearmodifiers: true
```
